/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Tue Jul 19 10:17:41 2016. */

#ifndef PB_SENSOR_MESSAGE_PB_H_INCLUDED
#define PB_SENSOR_MESSAGE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _sensors {
    int32_t id;
    bool has_batmon_temp;
    int32_t batmon_temp;
    bool has_batmon_volt;
    int32_t batmon_volt;
    bool has_opt_3001;
    int32_t opt_3001;
    bool has_bme_280_temp;
    int32_t bme_280_temp;
    bool has_bme_280_pres;
    int32_t bme_280_pres;
    bool has_bme_280_hum;
    int32_t bme_280_hum;
    bool has_LIS2DE12_x;
    int32_t LIS2DE12_x;
    bool has_LIS2DE12_y;
    int32_t LIS2DE12_y;
    bool has_LIS2DE12_z;
    int32_t LIS2DE12_z;
    bool has_lis3mdl_x;
    int32_t lis3mdl_x;
    bool has_lis3mdl_y;
    int32_t lis3mdl_y;
    bool has_lis3mdl_z;
    int32_t lis3mdl_z;
    bool has_pir;
    bool pir;
/* @@protoc_insertion_point(struct:sensors) */
} sensors;

/* Default values for struct fields */

/* Initializer values for message structs */
#define sensors_init_default                     {0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define sensors_init_zero                        {0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define sensors_id_tag                           1
#define sensors_batmon_temp_tag                  2
#define sensors_batmon_volt_tag                  3
#define sensors_opt_3001_tag                     4
#define sensors_bme_280_temp_tag                 5
#define sensors_bme_280_pres_tag                 6
#define sensors_bme_280_hum_tag                  7
#define sensors_LIS2DE12_x_tag                   8
#define sensors_LIS2DE12_y_tag                   9
#define sensors_LIS2DE12_z_tag                   10
#define sensors_lis3mdl_x_tag                    11
#define sensors_lis3mdl_y_tag                    12
#define sensors_lis3mdl_z_tag                    13
#define sensors_pir_tag                          14

/* Struct field encoding specification for nanopb */
extern const pb_field_t sensors_fields[15];

/* Maximum encoded size of messages (where known) */
#define sensors_size                             110

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SENSOR_MESSAGE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
