# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor_message.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x14sensor_message.proto\"\x94\x02\n\x07sensors\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x13\n\x0b\x62\x61tmon_temp\x18\x02 \x01(\x05\x12\x13\n\x0b\x62\x61tmon_volt\x18\x03 \x01(\x05\x12\x10\n\x08opt_3001\x18\x04 \x01(\x05\x12\x14\n\x0c\x62me_280_temp\x18\x05 \x01(\x11\x12\x14\n\x0c\x62me_280_pres\x18\x06 \x01(\x05\x12\x13\n\x0b\x62me_280_hum\x18\x07 \x01(\x05\x12\x12\n\nLIS2DE12_x\x18\x08 \x01(\x11\x12\x12\n\nLIS2DE12_y\x18\t \x01(\x11\x12\x12\n\nLIS2DE12_z\x18\n \x01(\x11\x12\x11\n\tlis3mdl_x\x18\x0b \x01(\x11\x12\x11\n\tlis3mdl_y\x18\x0c \x01(\x11\x12\x11\n\tlis3mdl_z\x18\r \x01(\x11\x12\x0b\n\x03pir\x18\x0e \x01(\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SENSORS = _descriptor.Descriptor(
  name='sensors',
  full_name='sensors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sensors.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batmon_temp', full_name='sensors.batmon_temp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batmon_volt', full_name='sensors.batmon_volt', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='opt_3001', full_name='sensors.opt_3001', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bme_280_temp', full_name='sensors.bme_280_temp', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bme_280_pres', full_name='sensors.bme_280_pres', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bme_280_hum', full_name='sensors.bme_280_hum', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LIS2DE12_x', full_name='sensors.LIS2DE12_x', index=7,
      number=8, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LIS2DE12_y', full_name='sensors.LIS2DE12_y', index=8,
      number=9, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LIS2DE12_z', full_name='sensors.LIS2DE12_z', index=9,
      number=10, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lis3mdl_x', full_name='sensors.lis3mdl_x', index=10,
      number=11, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lis3mdl_y', full_name='sensors.lis3mdl_y', index=11,
      number=12, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lis3mdl_z', full_name='sensors.lis3mdl_z', index=12,
      number=13, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pir', full_name='sensors.pir', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=301,
)

DESCRIPTOR.message_types_by_name['sensors'] = _SENSORS

sensors = _reflection.GeneratedProtocolMessageType('sensors', (_message.Message,), dict(
  DESCRIPTOR = _SENSORS,
  __module__ = 'sensor_message_pb2'
  # @@protoc_insertion_point(class_scope:sensors)
  ))
_sym_db.RegisterMessage(sensors)


# @@protoc_insertion_point(module_scope)
